src/CIELO/EntrepriseBundle/Entity/Document.php
<?php

namespace CIELO\EntrepriseBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Document
 *
 * @ORM\Table(name="cielo_document")
 * @ORM\Entity(repositoryClass="CIELO\EntrepriseBundle\Entity\DocumentRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Document {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime", nullable=true)
     */
    private $date;

    /**
     * @var string
     *
     * @ORM\Column(name="lien", type="string", length=255, nullable=true)
     */
    private $lien;

    /**
     * @Assert\File(
     *      maxSize="1M",
     *      mimeTypes = {"image/png", "image/jpeg"},
     *      mimeTypesMessage = "Choisissez une image valide",
     *      maxSizeMessage = "L'image choisie est trop grande"
     * )
     */
    public $file;
    public $tempFilename;

    public function __construct() {
        $this->date = new \Datetime();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Document
     */
    public function setNom($nom) {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom() {
        return $this->nom;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Document
     */
    public function setDescription($description) {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription() {
        return $this->description;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Document
     */
    public function setDate($date) {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate() {
        return $this->date;
    }

    /**
     * Set lien
     *
     * @param string $lien
     * @return Document
     */
    public function setLien($lien) {
        $this->lien = $lien;

        return $this;
    }

    /**
     * Get lien
     *
     * @return string 
     */
    public function getLien() {
        return $this->lien;
    }

    public function getFile() {
        return $this->file;
    }

    public function setFile(UploadedFile $file) {
        $this->file = $file;
        if (null !== $this->lien) {
            $this->tempFilename = $this->lien;
            $this->lien = null;
            $this->nom = null;
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        if (null === $this->file) {
            return;
        }
        $this->lien = $this->file->guessExtension();
        $this->nom = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (null === $this->file) {
            return;
        }
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
        $this->file->move(
                $this->getUploadRootDir(), $this->id . '.' . $this->lien
        );
        /* $name = $this->file->getClientOriginalName();
          $this->file->move($this->getUploadRootDir(), $name);
          $this->lien = $name;
          $this->nom = $name; */
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload() {
        $this->tempFilename = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->lien;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload() {
        if (file_exists($this->tempFilename)) {
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir() {
        return 'uploads/img';
    }

    protected function getUploadRootDir() {
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    public function getAbsolutePath() {
        return null === $this->lien ? null : $this->getUploadRootDir() . '/' . $this->id . '.' . $this->lien;
    }

    public function getWebPath() {
        return $this->getUploadDir() . '/' . $this->getId() . '.' . $this->getLien();
    }

    public function getLink() {
//        return "http://" . $_SERVER["HTTP_HOST"] . "/cielo-market-build2040308/web/app_dev.php/service/image/" . $this->id;
        return "http://" . $_SERVER["HTTP_HOST"] . "/service/image/" . $this->id;
    }

}

src/CIELO/EntrepriseBundle/Resources/views/layout.html.twig
{# empty Twig template #}
{%extends "::global_admin_layout.html.twig"%}

{% block body %}
<div class="container-fluid">

    <!-- Header starts -->
    {%block enteteEntreprise%}
    <div class="row-fluid">
        <div class="span12">

            <div class="header-top">

                <div class="header-wrapper">

                    <a href="#" class="utopia-logo">
                        <img src="{{asset(app.user.entreprise.document.webPath)}}" alt="Utopia" style="max-height: 50px; max-width: 200px;">
                        <span style="font-size: 20px;">{{ app.user.entreprise.nom }}</span>
                    </a>
                    
                    <div class="header-right">
                        <div class="search-panel header-divider">
                            <div class="">
                                <form action="{{path('cielo_enterprise_recherche')}}" method="post" style="">
                                    <input style="width: 150px" type="text" name="searchContent" placeholder="Recherche...">
                                    <select style="width: 150px" name="searchType">
                                        <option value="produit">Produit</option>
                                        <option value="categorie">Catégorie</option>
                                    </select>
                                    <input type="submit" value="Valider"/>
                                </form>
                            </div>
                        </div>
                        <div class="header-divider">&nbsp;</div>
                        <div class="user-panel header-divider">
                                <div class="user-info">
                                    <img src="{{asset('bundles/cieloadmin/admin/img/icons/user.png')}}" alt="">
                                    {%if is_granted("IS_AUTHENTICATED_REMEMBERED")%}
                                        <a href="#">{{ app.user.username }}</a>
                                    {%endif%}
                                </div>

                                <div class="user-dropbox">
                                    <ul>
                                        <li class="theme-changer dark-theme"><a href="javascript:void(0)" class="dark" rel="{{asset('bundles/cieloadmin/admin/css/themes/utopia-dark.css?v18')}}" >Dark theme</a></li>
                                        <li class="theme-changer white-theme"><a href="javascript:void(0)" class="white" rel="{{asset('bundles/cieloadmin/admin/css/utopia-white.css?v19')}}" >White theme</a></li>
                                        <li class="theme-changer siteclient"><a href="{{path('cielo_user_homepage')}}" class="white" rel="{{asset('bundles/cieloadmin/admin/css/utopia-white.css?v19')}}" >Accéder au Site client</a></li>
                                        <li class="logout"><a href="{{path('cielo_admin_entreprise_logout')}}">Déconnexion</a></li>
                                    </ul>
                                </div>

                         </div><!-- User panel end -->

                    </div><!-- End header right -->

                </div><!-- End header wrapper -->

            </div><!-- End header -->

        </div>

    </div>
    {%endblock enteteEntreprise%}

    <!-- Header ends -->

    <div class="row-fluid">

        <!-- Sidebar statrt -->
        <div class="span2 sidebar-container">

            <div class="sidebar">

                <div class="navbar sidebar-toggle">
                    <div class="container">

                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>

                    </div>
                </div>
                {%block menuEntreprise%}
                <div class="nav-collapse collapse leftmenu collapse" style="height: 0px;">

                    <ul>
                        <li class="current"><a class="dashboard smronju" href="{{path('cielo_enterprise_homepage')}}" title="Tableau de bord"><span>Tableau de bord</span></a></li>
                        <li><a class="categoriebri" href="{{path('cielo_enterprise_categories')}}" title="Catégories"><span>Catégories</span></a> </li>
                        <li><a class="produitbri" href="{{path('cielo_enterprise_produit')}}" title="Produits"><span>Produits</span></a></li>
                        <li><a class="promotionbri" href="{{path('cielo_enterprise_promotion')}}" title="Promotion"><span>Promotions</span></a></li>
                        <li><a class="jeubri" href="{{path('cielo_enterprise_campagne_list')}}" title="Jeux"><span>Campagne</span></a></li>
                        <li><a class="adminbri" href="{{path('cielo_enterprise_administration_entreprise')}}" title="Administration"><span>Administration</span></a></li>
                    </ul>

                </div>
                {%endblock menuEntreprise%}

            </div>
        </div>

        <!-- Sidebar end -->
        {% block bodyFils1 %}

        {% endblock bodyFils1 %}
    </div>

    <!-- Maincontent end -->

</div> <!-- end of container -->

{% endblock body %}